### ISSUE TITLE
Multiple loadHandlers registered in node

### ISSUE THREAD

**Issue by tafsiri** [tensorflow/tfjs#1447]
#### TensorFlow.js version
"@tensorflow/tfjs": "1.0.2",
"@tensorflow/tfjs-node": "1.0.2",
"@tensorflow-models/universal-sentence-encoder": "1.0.1",

#### Browser version
It exhibits in node.js though the issue itself may be in core.

#### Describe the problem or feature request
Using the above packages and the code below you get the following error. 

```
UnhandledPromiseRejectionWarning: Error: Found more than one (2) load handlers for URL 'https://storage.googleapis.com/tfjs-models/savedmodel/universal_sentence_encoder/model.json'
```

Multiple load handlers are being registered. This isue dows not occur with union package 1.0.1

#### Code to reproduce the bug / link to feature request

```
const tf = require('@tensorflow/tfjs-node');
global.fetch = require('node-fetch');
const useLoader = require('@tensorflow-models/universal-sentence-encoder');

(async function run() {
  console.time('Loading Universal Sentence Encoder');
  const use = await useLoader.load();
  console.timeEnd('Loading Universal Sentence Encoder');
})()
```

**Comment by caisq** [comment]
@tafsiri My guess is that universal-sentence-encoder is based on a different version of tfjs-node than the tfjs-node you are explicitly importing, causing the HTTP load handler to be registered twice.

**Comment by tafsiri** [comment]
@caisq, tfjs is peerDependency for USE, so i don't think it can directly cause a problem. I do have both tfjs and tfjs-node in my package json (and here they are the exact same version), I don't think that should cause a problem either since i only import one of them. I suspect a similar bug would occur with other models.

**Comment by chenqing** [comment]
```
 Error: Found more than one (2) load handlers for URL 'file:///root/.escher/models/mobilenet/v1_1.0_224/model.json'
    at new ValueError (/usr/lib/node_modules/.../_@tensorflow_tfjs-layers@1.1.0@@tensorflow/tfjs-layers/dist/errors.js:68:28)
    at Object.<anonymous> (/usr/lib/node_modules/..._@tensorflow_tfjs-layers@1.1.0@@tensorflow/tfjs-layers/dist/models.js:248:27)
    at step (/usr/lib/node_modules/.../_@tensorflow_tfjs-layers@1.1.0@@tensorflow/tfjs-layers/dist/models.js:54:23)
    at Object.next (/usr/lib/node_modules/.../_@tensorflow_tfjs-layers@1.1.0@@tensorflow/tfjs-layers/dist/models.js:35:53)
    at /usr/lib/node_modules/.../_@tensorflow_tfjs-layers@1.1.0@@tensorflow/tfjs-layers/dist/models.js:29:71
```

**Comment by caisq** [comment]
@chenqing Can you show your code? Specially, I'm interested in how you imported tfjs and/or tfjs-node.

**Comment by nsthorat** [comment]
FYI this should be fixed in 1.1, we might have to update USE.

**Comment by chenqing** [comment]
> @chenqing Can you show your code? Specially, I'm interested in how you imported tfjs and/or tfjs-node.

```
let backgend;
if (process.env.ENABLE_GPU == 1) {
  backgend = require('@tensorflow/tfjs-node-gpu');
} else {
  backgend = require('@tensorflow/tfjs-node');
}
```

**Comment by nsthorat** [comment]
Oh apologies, this won't be fixed in 1.1, only double registration of http handlers will be. I'll fix file handling in the next release.

**Comment by axinging** [comment]
Hi, I meet similar problems when run PoseNet model with latest TFJS code.
The errors are:
```
Uncaught (in promise) Error: Found more than one (4) load handlers for URL 'https://storage.googleapis.com/tfjs-models/savedmodel/posenet/mobilenet/quant2/075/model-stride16.json'
    at GraphModel.findIOHandler (graph_model.ts:98)
    at GraphModel.load (graph_model.ts:111)
    at loadGraphModel (graph_model.ts:392)
    at posenet.esm.js:17
    at posenet.esm.js:17
    at Object.next (posenet.esm.js:17)
    at posenet.esm.js:17
    at new Promise (<anonymous>)
    at __awaiter (posenet.esm.js:17)
    at loadMobileNet (posenet.esm.js:17)
```
And How I run into this:
```
git clone https://github.com/tensorflow/tfjs.git && ^
cd tfjs && ^
yarn  & cd tfjs-core  && ^
yarn && yarn build-npm  && ^
yarn link  && ^
cd ../tfjs-converter  && ^
yarn && yarn build-npm  && ^
yarn link  && ^
cd ../tfjs-backend-cpu  && ^
yarn && yarn build  && ^
yarn link  && ^
cd ../tfjs-backend-webgl  && ^
yarn && yarn build  && ^
yarn link  && ^
cd ../tfjs-backend-webgpu  && ^
yarn && yarn build  && ^
yarn link  && ^
cd ../../    && ^
git clone https://github.com/tensorflow/tfjs-models.git && ^
cd tfjs-models  && ^
yarn    && ^
cd posenet    && ^
yarn link "@tensorflow/tfjs-core"   && ^
yarn link "@tensorflow/tfjs-backend-webgpu"   && ^
yarn link "@tensorflow/tfjs-converter"   && ^
yarn link "@tensorflow/tfjs-backend-webgl"   && ^
yarn && yarn build-npm   && ^
yarn link   && ^
cd demos   && ^
yarn link "@tensorflow/tfjs-core"   && ^
yarn link "@tensorflow/tfjs-backend-webgpu"   && ^
yarn link "@tensorflow/tfjs-backend-webgl"   && ^
yarn link "@tensorflow/tfjs-converter"   && ^
yarn link "@tensorflow-models/posenet"   && ^
yarn && yarn build   && ^
yarn watch
```

At first, I suspect some thing is wrong with my local environment. So I remove all links inside C:\Users\axing\AppData\Local\Yarn\Data\link, then delete all C:\Users\axing\AppData\Local\Yarn\Cache\v6\npm-@tensorflow-*

However, this still not work.

**Comment by gaikwadrahul8** [comment]
Hi, @tafsiri 

Apologize for the delayed response and I was able to replicate the same issue without any error with latest versions so for your reference I have added screenshot below with package.json dependancies so please try it out from your end and let's know whether your issue is resolving or not ? Thank you!

Here screenshot for your reference :

![image](https://user-images.githubusercontent.com/115997457/228057306-cb42ee9b-1921-4058-9a9f-77aa697997b0.png)

Here is package.json details :

```
{
  "dependencies": {
    "@tensorflow-models/universal-sentence-encoder": "^1.3.3",
    "@tensorflow/tfjs": "^4.2.0",
    "@tensorflow/tfjs-node": "^4.2.0"
  }
}

```

**Comment by davehorner** [comment]
I am experiencing this trying to use the upload_video example.  If anyone has any suggestions; i have the latest source and I'm using the package.json that is in the demos/upload_video folder.
