### ISSUE TITLE
Incorrect handling of quantized efficientdet models

### ISSUE THREAD

**Issue by rafallukasik123** [tensorflow/tfjs#4408]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow.js): yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): windows 10
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) : ipad mini 5  ios 14.0.1
- TensorFlow.js installed from (npm or script link): npm
- TensorFlow.js version (use command below):  2.7
- Browser version: Chrome 87
- Tensorflow.js Converter Version: 2.7

**Describe the current behavior**

At the beginning  i donwload efficientdet from https://tfhub.dev/tensorflow/efficientdet/d1/1?tf-hub-format=compressed
After that i use following command : 
**tensorflowjs_converter --input_format=tf_saved_model --signature_name=serving_default --quantize_float16 --output_format=tfjs_graph_model ./efficiendet_from_tfhub ./webformat**
Next i predict image in my script and receives the following resaults : 
![image](https://user-images.githubusercontent.com/38047112/102222429-b16ad900-3ee3-11eb-8b9b-2611fccdfd35.png)

In  resault i have three the same bb. 
Is depending on the results of the prediction - such this cases may be more

Additionally when i set flag tf.ENV.set('WEBGL_CHECK_NUMERICAL_PROBLEMS', true) i have error : 
 "Error: The value 65504 cannot be represented on this device."

It is important in my script i set the following tf flags : 
tf.ENV.set('WEBGL_RENDER_FLOAT32_CAPABLE', false);
tf.ENV.set('WEBGL_RENDER_FLOAT32_ENABLED', false);

**Describe the expected behavior**
If i set tf flags as following - we will use the float32 its work fine : 
tf.ENV.set('WEBGL_RENDER_FLOAT32_CAPABLE', true);
tf.ENV.set('WEBGL_RENDER_FLOAT32_ENABLED', true);

![image](https://user-images.githubusercontent.com/38047112/102223229-b67c5800-3ee4-11eb-9aea-be33a079d8fa.png)

Its looks  like quantization is work bad

I must set tf flags in the first way because i try to run efficiendet model on my ipad mini 5 and webkit doesn't support 32-bit float.

**Comment by rthadur** [comment]
it depends on the device which you are running , please check here for more info as how to use the flag https://www.tensorflow.org/js/guide/platform_environment#precision

**Comment by rafallukasik123** [comment]
I understand. But my device doesn't support flaot32. So my flags WEBGL_RENDER_FLOAT32_CAPABLE and WEBGL_RENDER_FLOAT32_ENABLED have false value.
I wanted to run model so I quantized model with option --quantize_float16 during the conversion.
so if it doesn't work it's not a bug? i think quantization should solve this problem.
Or is there any other way to run model on a device that doesn't support float 32?

**Comment by pyu10055** [comment]
@rafallukasik123 I am curious what type of device you are having that does not support float32? on a side note, for device that does not support float32 texture, quantization the model would not help address the precision problem. Since the model is not trained with float16 weights, you will still get the accuracy loss. One possible work around is to use web assembly backend instead.

**Comment by rafallukasik123** [comment]
I wrote above, I try to run model  on the Apple iPad mini 5. Unfortunately webkit on mobile devices doesn't support float32 texture.

**Comment by rafallukasik123** [comment]
@pyu10055 I trained model with parameter  use_bfloat16: true(folder saved_model). 
Unfortunately it still didn't help.
