### ISSUE TITLE
Tensor is disposed too early for FaceLandmarkDetection&architecture=attention_mesh

### ISSUE THREAD

**Issue by axinging** [tensorflow/tfjs#7445]
Reproduce:  
```
Run e2e with url flag 
tfjs//e2e/benchmarks/local-benchmark/?task=performance&benchmark=FaceLandmarkDetection&architecture=attention_mesh&backend=cpu&WEBGL_USE_SHAPES_UNIFORMS=true&CHECK_COMPUTATION_FOR_ERRORS=false&warmup=50&run=50&profile=50&localBuild=core,converter,cpu,webgl,webgpu
```

Error:
```
Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'backend')
    at Engine.moveData (engine.ts:426:29)
    at DataStorage.get (backend.ts:55:22)
    at Object.reshape [as kernelFunc] (Reshape.ts:44:41)
    at kernelFunc (engine.ts:647:22)
    at engine.ts:713:23
    at Engine.scopedRun (engine.ts:480:19)
    at Engine.runKernelFunc (engine.ts:709:10)
    at Engine.runKernel (engine.ts:554:17)
    at reshape_ (reshape.ts:60:17)
    at Object.reshape__op [as reshape] (operation.ts:51:24)
```
Possible change related to this issue: https://github.com/tensorflow/tfjs/pull/7392

**Comment by pyu10055** [comment]
@axinging Is this an issue on webGPU or WebGL backend?

**Comment by chunnienc** [comment]
It appears to be what #7431 trying to fix. I about to merge this PR but I'll modify that a little bit before merging. You may path it first and see if there is still an issue.

**Comment by axinging** [comment]
> @axinging Is this an issue on webGPU or WebGL backend?
@pyu10055, This can be reproduced on CPU/WebGL/WebGPU backends.

**Comment by chunnienc** [comment]
@axinging I've merged my PR to master and verified that this error no longer appears.

**Comment by gaikwadrahul8** [comment]
Hi, @axinging 

Apologize for the delayed response and It seems like to take care of this issue this PR https://github.com/tensorflow/tfjs/pull/7505 was submitted and now that PR got merged so your issues should be fixed so could you please give it try from your end and let us know whether have we taken care your issue or not ? 

If issue still persists please let us know ? Thank you!
