### ISSUE TITLE
face-landmarks-detection dependency conflict

### ISSUE THREAD

**Issue by aptxyz** [tensorflow/tfjs#7905]
<em>Please make sure that this is a build/installation issue. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:build_template</em>

**System information**
- Win 11 Pro 22H2 22621.2134
- node v20.3.0
- npm 9.6.7

**Describe the problem**

npm install @tensorflow-models/face-landmarks-detection
> npm ERR! code ERESOLVE
> npm ERR! ERESOLVE unable to resolve dependency tree
> npm ERR!
> npm ERR! While resolving: undefined@undefined
> npm ERR! Found: @tensorflow/tfjs-backend-webgl@4.10.0
> npm ERR! node_modules/@tensorflow/tfjs-backend-webgl
> npm ERR!   peer @tensorflow/tfjs-backend-webgl@"^4.4.0" from @tensorflow-models/face-detection@1.0.2
> npm ERR!   node_modules/@tensorflow-models/face-detection
> npm ERR!     @tensorflow-models/face-detection@"^1.0.1" from the root project
> npm ERR!     peer @tensorflow-models/face-detection@"~1.0.0" from @tensorflow-models/face-landmarks-detection@1.0.5
> npm ERR!     node_modules/@tensorflow-models/face-landmarks-detection
> npm ERR!       @tensorflow-models/face-landmarks-detection@"*" from the root project
> npm ERR!
> npm ERR! Could not resolve dependency:
> npm ERR! peer @tensorflow/tfjs-backend-webgl@"^3.12.0" from @tensorflow-models/face-landmarks-detection@1.0.5
> npm ERR! node_modules/@tensorflow-models/face-landmarks-detection
> npm ERR!   @tensorflow-models/face-landmarks-detection@"*" from the root project
> npm ERR!
> npm ERR! Fix the upstream dependency conflict, or retry
> npm ERR! this command with --force or --legacy-peer-deps
> npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
> npm ERR!
> npm ERR!
> npm ERR! For a full report see:
> npm ERR! C:\Users\User\AppData\Local\npm-cache\_logs\2023-08-13T02_50_36_950Z-eresolve-report.txt

![image](https://github.com/tensorflow/tfjs/assets/4888724/6467b443-2202-40d8-9a74-db3f63ec77c0)

dependency conflict, the face landmarks detection model use tfjs v3, however the model 'face-detection@1.0.2' update tfjs from v3 to v4

**Comment by gaikwadrahul8** [comment]
Hi, @aptxyz 

Apologize for the delayed response and thank you for bringing this issue to our attention, I checked `@tensorflow-models/face-landmarks-detection` and it's using this version `"^3.12.0"` and for this package `@tensorflow-models/face-detection@1.0.2` it's using `"^4.4.0"`

Could you please try to use this package version `@tensorflow-models/face-detection@1.0.1` where it's using this version `"^3.14.0"` and let us know whether is it working as expected or not ? 

We'll dig more into this issue with dependancies conflict and if possible we'll try to update package dependancies for `@tensorflow-models/face-landmarks-detection` to `V4` because it's using the V3 package versions. Thank you!

**Comment by aptxyz** [comment]
I think I did tried install all three together `face-detection@1.0.1` along with `tfjs@3` & `face-landmarks-detection@1.0.2` without warning, and it's working as expected.  But I eventually just download models from tfhub and use `tfjs@4` as backend for various reasons.

**Comment by JacobRMiller** [comment]
I'm running into the same issue. I also tried `face-detection@1.0.1` along with `tfjs@3 `and `face-landmarks-detection@1.0.2` without success.

**Comment by Johnrobmiller** [comment]
This was never resolved. A maintainer ought to fix this!

**Comment by maazcloudhire** [comment]
Can someone please fix this?

**Comment by maazcloudhire** [comment]
I did --legacy-peer-deps. but now It's creating an issue in production.

**Comment by klimeryk** [comment]
Can confirm the issue still exists. Can't even run the demos from the official repository.

**Comment by mattsoulanille** [comment]
This should now be fixed as of face-landmarks-detection 1.0.6, and it should no longer request version 3 and 4 of TFJS at the same time. I'll reopen this for now until I get confirmation that the fix works for your project.

**Comment by klimeryk** [comment]
@mattsoulanille, thank you so much for the follow-up! [I've tested on a branch](https://github.com/klimeryk/dealwithit/commit/8470def64c559ffbc94324f0616de4b214835688) for my project and can confirm that the dependency conflict has been resolved 🎉 So this issue can be closed 🙇 
However, for my use case, the library still cannot be used in production due to https://github.com/tensorflow/tfjs/issues/8290. Looks like this model (maybe others?) are not compatible with https://vitejs.dev/ It would be hugely helpful if you could have a look if there's anything that can be done to fix that situation 🙏

**Comment by nileshau-afk** [comment]
Hi @klimeryk , @aptxyz , 

Thank you for the update and for sharing your experience. I will go ahead and close this issue for now. Please feel free to reopen this issue, if you or anyone else encounters further difficulties. 

Thank you for your understanding.
